spring.application.name=maosquedoam
spring.datasource.url=jdbc:postgresql://localhost:5432/maosquedoam
spring.datasource.username=postgres
spring.datasource.password=murilo

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
