spring.application.name=maosquedoam
spring.datasource.url=jdbc:postgresql://localhost:5432/maosquedoam
spring.datasource.username=postgres
spring.datasource.password=murilo

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=freitasmuriloduarte@gmail.com
spring.mail.password=xsrp xxcf fuhy pgqd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
logging.level.org.springframework.security=DEBUG

server.port=8080
